package controller

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"time"

	infrav1 "github.com/kommodity-io/cluster-api-provider-bringyourowntalos/api/v1alpha1"
	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime"
	clusterv1 "sigs.k8s.io/cluster-api/api/v1beta1"
	"sigs.k8s.io/cluster-api/util"
	"sigs.k8s.io/cluster-api/util/conditions"
	"sigs.k8s.io/cluster-api/util/finalizers"
	"sigs.k8s.io/cluster-api/util/patch"
	ctrl "sigs.k8s.io/controller-runtime"
	ctrlclient "sigs.k8s.io/controller-runtime/pkg/client"
	ctrlcontroller "sigs.k8s.io/controller-runtime/pkg/controller"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	"sigs.k8s.io/controller-runtime/pkg/log"
)

const (
	// byotMachineFinalizer protects ByotMachine resources during deletion.
	byotMachineFinalizer = "byotmachine.infrastructure.cluster.x-k8s.io"

	// bootstrapSecretDataKey is the key holding the Talos machine
	// configuration in the bootstrap data secret.
	bootstrapSecretDataKey = "value"

	// clusterTalosConfigSecretSuffix is the suffix of the secret holding the
	// cluster's talosconfig, generated by the Talos bootstrap provider.
	clusterTalosConfigSecretSuffix = "-talosconfig" //nolint:gosec // Not a credential: file name suffix.

	// talosConfigSecretDataKey is the key holding the talosconfig document in
	// talosconfig secrets.
	talosConfigSecretDataKey = "talosconfig"

	// requeueAfterBootstrap is the delay used while waiting for bootstrap data.
	requeueAfterBootstrap = 10 * time.Second
)

// MachineAdoptedCondition reports whether the machine configuration has been
// applied to the adopted machine.
const MachineAdoptedCondition clusterv1.ConditionType = "MachineAdopted"

// ByotMachineReconciler reconciles a ByotMachine object.
type ByotMachineReconciler struct {
	Client ctrlclient.Client
	Scheme *runtime.Scheme
}

// NewByotMachineReconciler creates a new ByotMachineReconciler.
func NewByotMachineReconciler(client ctrlclient.Client) *ByotMachineReconciler {
	return &ByotMachineReconciler{
		Client: client,
		Scheme: client.Scheme(),
	}
}

// SetupWithManager sets up the controller with the Manager.
func (r *ByotMachineReconciler) SetupWithManager(
	manager ctrl.Manager,
	options ctrlcontroller.Options,
) error {
	err := ctrl.NewControllerManagedBy(manager).
		For(&infrav1.ByotMachine{}).
		WithOptions(options).
		Complete(r)
	if err != nil {
		return fmt.Errorf("failed to build ByotMachine controller: %w", err)
	}

	return nil
}

// +kubebuilder:rbac:groups=infrastructure.cluster.x-k8s.io,resources=byotmachines,verbs=get;list;watch;update;patch
// +kubebuilder:rbac:groups=infrastructure.cluster.x-k8s.io,resources=byotmachines,verbs=create;delete
// +kubebuilder:rbac:groups=infrastructure.cluster.x-k8s.io,resources=byotmachines/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=infrastructure.cluster.x-k8s.io,resources=byotmachines/finalizers,verbs=update
// +kubebuilder:rbac:groups=cluster.x-k8s.io,resources=machines;machines/status,verbs=get;list;watch
// +kubebuilder:rbac:groups="",resources=secrets,verbs=get;list;watch

// Reconcile adopts the Talos machine referenced by the ByotMachine.
func (r *ByotMachineReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	byotMachine := &infrav1.ByotMachine{}

	err := r.Client.Get(ctx, req.NamespacedName, byotMachine)
	if err != nil {
		if apierrors.IsNotFound(err) {
			return ctrl.Result{}, nil
		}

		return ctrl.Result{}, fmt.Errorf("failed to get ByotMachine %s: %w", req.NamespacedName, err)
	}

	if !byotMachine.DeletionTimestamp.IsZero() {
		// Adoption is a one-way operation in v1: nothing to undo on the host.
		// Authenticated reset back to maintenance mode is a planned follow-up.
		if controllerutil.RemoveFinalizer(byotMachine, byotMachineFinalizer) {
			err = r.Client.Update(ctx, byotMachine)
			if err != nil {
				return ctrl.Result{}, fmt.Errorf("failed to remove finalizer from ByotMachine %s: %w", req.NamespacedName, err)
			}
		}

		return ctrl.Result{}, nil
	}

	_, err = finalizers.EnsureFinalizer(ctx, r.Client, byotMachine, byotMachineFinalizer)
	if err != nil {
		return ctrl.Result{}, fmt.Errorf("failed to add finalizer to ByotMachine %s: %w", req.NamespacedName, err)
	}

	result, err := r.adopt(ctx, byotMachine)
	if err != nil {
		return result, fmt.Errorf("failed to adopt ByotMachine %s: %w", req.NamespacedName, err)
	}

	return result, nil
}

func (r *ByotMachineReconciler) adopt(ctx context.Context, byotMachine *infrav1.ByotMachine) (ctrl.Result, error) {
	logger := log.FromContext(ctx)

	patchHelper, err := patch.NewHelper(byotMachine, r.Client)
	if err != nil {
		return ctrl.Result{}, fmt.Errorf("failed to create patch helper: %w", err)
	}

	machine, machineConfig, wait, err := r.adoptionInputs(ctx, byotMachine)
	if err != nil {
		return ctrl.Result{}, err
	}

	if wait != nil {
		return *wait, nil
	}

	configHash := sha256Hex(machineConfig)

	if configUnchanged(byotMachine, configHash) {
		return ctrl.Result{}, nil
	}

	talosConfig, result, err := r.resolveTalosConfig(ctx, machine, byotMachine)
	if err != nil {
		return ctrl.Result{}, err
	}

	if result != nil {
		return *result, nil
	}

	err = applyMachineConfig(ctx, byotMachine.Spec.PublicIP, machineConfig, talosConfig)
	if err != nil {
		return ctrl.Result{}, r.recordApplyFailure(ctx, patchHelper, byotMachine, err)
	}

	markAdopted(byotMachine, configHash)

	err = patchHelper.Patch(ctx, byotMachine)
	if err != nil {
		return ctrl.Result{}, fmt.Errorf("failed to patch ByotMachine: %w", err)
	}

	logger.Info("Machine adopted", "byotMachine", byotMachine.Name, "publicIP", byotMachine.Spec.PublicIP)

	return ctrl.Result{}, nil
}

// adoptionInputs resolves the owner Machine and its bootstrap data. A non-nil
// wait result means one of them is not available yet; the caller should
// requeue with it.
func (r *ByotMachineReconciler) adoptionInputs(
	ctx context.Context,
	byotMachine *infrav1.ByotMachine,
) (*clusterv1.Machine, []byte, *ctrl.Result, error) {
	logger := log.FromContext(ctx)

	machine, err := util.GetOwnerMachine(ctx, r.Client, byotMachine.ObjectMeta)
	if err != nil {
		return nil, nil, nil, fmt.Errorf("failed to get owner Machine: %w", err)
	}

	if machine == nil {
		logger.Info("Waiting for Machine controller to set OwnerReference", "byotMachine", byotMachine.Name)

		return nil, nil, &ctrl.Result{RequeueAfter: requeueAfterBootstrap}, nil
	}

	machineConfig, err := r.bootstrapData(ctx, machine)
	if errors.Is(err, ErrBootstrapDataNotReady) {
		logger.Info("Waiting for bootstrap data", "byotMachine", byotMachine.Name, "machine", machine.Name)

		return nil, nil, &ctrl.Result{RequeueAfter: requeueAfterBootstrap}, nil
	}

	if err != nil {
		return nil, nil, nil, err
	}

	return machine, machineConfig, nil, nil
}

// recordApplyFailure marks the adoption condition false, persists it, and
// returns the apply error as the reconcile failure.
func (r *ByotMachineReconciler) recordApplyFailure(
	ctx context.Context,
	patchHelper *patch.Helper,
	byotMachine *infrav1.ByotMachine,
	applyErr error,
) error {
	conditions.MarkFalse(
		byotMachine,
		MachineAdoptedCondition,
		"ApplyFailed",
		clusterv1.ConditionSeverityWarning,
		"%s",
		applyErr.Error(),
	)

	err := patchHelper.Patch(ctx, byotMachine)
	if err != nil {
		return fmt.Errorf("failed to patch ByotMachine after apply failure: %w", err)
	}

	return applyErr
}

// markAdopted updates the ByotMachine spec and status after a successful
// machine configuration apply.
func markAdopted(byotMachine *infrav1.ByotMachine, configHash string) {
	providerID := infrav1.ProviderIDPrefix + byotMachine.Spec.PublicIP

	byotMachine.Spec.ProviderID = &providerID
	byotMachine.Status.Ready = true
	byotMachine.Status.LastAppliedConfigSHA = configHash
	byotMachine.Status.Addresses = []clusterv1.MachineAddress{
		{
			Type:    clusterv1.MachineExternalIP,
			Address: byotMachine.Spec.PublicIP,
		},
	}

	conditions.MarkTrue(byotMachine, MachineAdoptedCondition)
}

// configUnchanged reports whether the machine is already adopted with the
// same configuration that would be applied now.
func configUnchanged(byotMachine *infrav1.ByotMachine, configHash string) bool {
	return byotMachine.Status.Ready &&
		byotMachine.Spec.ProviderID != nil &&
		byotMachine.Status.LastAppliedConfigSHA == configHash
}

func sha256Hex(data []byte) string {
	sum := sha256.Sum256(data)

	return hex.EncodeToString(sum[:])
}

// bootstrapData reads the Talos machine configuration produced by the
// bootstrap provider for the given Machine.
func (r *ByotMachineReconciler) bootstrapData(
	ctx context.Context,
	machine *clusterv1.Machine,
) ([]byte, error) {
	if machine.Spec.Bootstrap.DataSecretName == nil {
		return nil, ErrBootstrapDataNotReady
	}

	secret := &corev1.Secret{}
	secretKey := ctrlclient.ObjectKey{
		Namespace: machine.Namespace,
		Name:      *machine.Spec.Bootstrap.DataSecretName,
	}

	err := r.Client.Get(ctx, secretKey, secret)
	if err != nil {
		if apierrors.IsNotFound(err) {
			return nil, ErrBootstrapDataNotReady
		}

		return nil, fmt.Errorf("failed to get bootstrap secret %s: %w", secretKey, err)
	}

	data, ok := secret.Data[bootstrapSecretDataKey]
	if !ok || len(data) == 0 {
		return nil, ErrBootstrapDataEmpty
	}

	return data, nil
}

// resolveTalosConfig picks the talosconfig to authenticate with, and returns
// nil for machines still in maintenance mode. A non-nil result signals the
// reconcile should requeue while the needed secret becomes available.
func (r *ByotMachineReconciler) resolveTalosConfig(
	ctx context.Context,
	machine *clusterv1.Machine,
	byotMachine *infrav1.ByotMachine,
) ([]byte, *ctrl.Result, error) {
	logger := log.FromContext(ctx)

	// Re-application on an already-configured machine: use the cluster's own
	// talosconfig (the machine carries our PKI since its first apply).
	if byotMachine.Status.Ready {
		talosConfig, err := r.clusterTalosConfig(ctx, machine.Spec.ClusterName, byotMachine.Namespace)
		if errors.Is(err, ErrClusterTalosConfigNotReady) {
			logger.Info("Waiting for cluster talosconfig", "byotMachine", byotMachine.Name)

			return nil, &ctrl.Result{RequeueAfter: requeueAfterBootstrap}, nil
		}

		return talosConfig, nil, err
	}

	// Foreign machine takeover: use the talosconfig of its CURRENT setup.
	if byotMachine.Spec.TalosConfigSecretRef != nil {
		talosConfig, err := r.referencedTalosConfig(ctx, byotMachine.Spec.TalosConfigSecretRef.Name, byotMachine.Namespace)
		if errors.Is(err, ErrClusterTalosConfigNotReady) {
			logger.Info("Waiting for referenced talosconfig secret", "byotMachine", byotMachine.Name)

			return nil, &ctrl.Result{RequeueAfter: requeueAfterBootstrap}, nil
		}

		return talosConfig, nil, err
	}

	return nil, nil, nil
}

// clusterTalosConfig loads the talosconfig generated by the bootstrap provider
// for the given cluster (secret "<cluster>-talosconfig").
func (r *ByotMachineReconciler) clusterTalosConfig(
	ctx context.Context,
	clusterName string,
	namespace string,
) ([]byte, error) {
	return r.referencedTalosConfig(ctx, clusterName+clusterTalosConfigSecretSuffix, namespace)
}

// referencedTalosConfig loads a talosconfig document from a secret in the
// same namespace. A missing secret is treated as a not-ready state.
func (r *ByotMachineReconciler) referencedTalosConfig(
	ctx context.Context,
	secretName string,
	namespace string,
) ([]byte, error) {
	secret := &corev1.Secret{}
	secretKey := ctrlclient.ObjectKey{
		Namespace: namespace,
		Name:      secretName,
	}

	err := r.Client.Get(ctx, secretKey, secret)
	if err != nil {
		if apierrors.IsNotFound(err) {
			return nil, ErrClusterTalosConfigNotReady
		}

		return nil, fmt.Errorf("failed to get talosconfig secret %s: %w", secretKey, err)
	}

	data, ok := secret.Data[talosConfigSecretDataKey]
	if !ok || len(data) == 0 {
		return nil, ErrClusterTalosConfigNotReady
	}

	return data, nil
}
