package controller

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"maps"
	"strconv"
	"time"

	infrav1 "github.com/kommodity-io/cluster-api-provider-bringyourowntalos/api/v1alpha1"
	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	clusterv1 "sigs.k8s.io/cluster-api/api/v1beta1"
	"sigs.k8s.io/cluster-api/controllers/clustercache"
	"sigs.k8s.io/cluster-api/util"
	"sigs.k8s.io/cluster-api/util/conditions"
	"sigs.k8s.io/cluster-api/util/finalizers"
	"sigs.k8s.io/cluster-api/util/patch"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/builder"
	ctrlclient "sigs.k8s.io/controller-runtime/pkg/client"
	ctrlcontroller "sigs.k8s.io/controller-runtime/pkg/controller"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	"sigs.k8s.io/controller-runtime/pkg/event"
	"sigs.k8s.io/controller-runtime/pkg/log"
)

const (
	// byotMachineFinalizer protects ByotMachine resources during deletion.
	byotMachineFinalizer = "byotmachine.infrastructure.cluster.x-k8s.io"

	// bootstrapSecretDataKey is the key holding the Talos machine
	// configuration in the bootstrap data secret.
	bootstrapSecretDataKey = "value"

	// clusterTalosConfigSecretSuffix is the suffix of the secret holding the
	// cluster's talosconfig, generated by the Talos bootstrap provider.
	clusterTalosConfigSecretSuffix = "-talosconfig" //nolint:gosec // Not a credential: file name suffix.

	// talosConfigSecretDataKey is the key holding the talosconfig document in
	// talosconfig secrets.
	talosConfigSecretDataKey = "talosconfig"

	// requeueAfterBootstrap is the delay used while waiting for bootstrap data.
	requeueAfterBootstrap = 10 * time.Second

	// requeueAfterResetIssued is the delay used while waiting for a machine
	// to come back in maintenance mode after a reset.
	requeueAfterResetIssued = 10 * time.Second

	// clusterNameLabel is the CAPI label carrying the owning cluster name.
	clusterNameLabel = "cluster.x-k8s.io/cluster-name"

	// kubeletServiceID is the Talos service restarted after a bundle-match
	// re-adoption so the workload-cluster Node is re-registered.
	kubeletServiceID = "kubelet"

	// requeueAfterNodeLink is the delay between two attempts to retrigger the
	// owning CAPI Machine's node-link reconciliation after adoption.
	requeueAfterNodeLink = 30 * time.Second

	// requeueAfterUpgrade is the fixed requeue delay while the post-adoption
	// upgrade state machine is in flight (InFlight version poll). No backoff
	// state; the controller requeues at this cadence.
	requeueAfterUpgrade = 30 * time.Second

	// versionProbeThreshold is the consecutive pre-upgrade Version RPC failure
	// count before the controller gives up and marks TalosVersionReady
	// False/VersionProbeFailed (stops retrying).
	versionProbeThreshold int32 = 5

	// upgradeThreshold is the consecutive post-upgrade Version RPC failure
	// count before the controller gives up and marks TalosVersionReady
	// False/UpgradeFailed (stops retrying).
	upgradeThreshold int32 = 10

	// nodeLinkRetriggerAnnotation is bumped on an adopted ByotMachine whose
	// owning Machine has not yet linked its workload Node (status.nodeRef).
	// Each bump changes the ByotMachine object, retriggers the CAPI Machine
	// controller (which watches the infra ref), and makes it re-list the
	// workload nodes to match spec.providerID. This compensates for the
	// control-plane bootstrap race where the workload API is down while the
	// Machine controller first reconciles, so its node watch never observes
	// the control-plane Node registering.
	nodeLinkRetriggerAnnotation = "infrastructure.cluster.x-k8s.io/node-link-retrigger"
)

// MachineAdoptedCondition reports whether the machine configuration has been
// applied to the adopted machine.
const MachineAdoptedCondition clusterv1.ConditionType = "MachineAdopted"

// JoinPreflightCondition reports the outcome of the join preflight: whether
// the machine is in maintenance mode (adoptable via the insecure client) or
// already carries this cluster's PKI bundle (re-adoptable via mTLS).
const JoinPreflightCondition clusterv1.ConditionType = "JoinPreflight"

// KubeletRestartNudgeCondition reports the outcome of the best-effort kubelet
// restart issued after a bundleMatch re-adopt so the workload Node re-registers
// (the machine already carries this cluster's PKI bundle, so the apply is
// authenticated rather than a fresh maintenance-mode adoption). Its failure is
// non-fatal: the configuration apply already succeeded and the kubelet
// (re)starts on boot regardless.
const KubeletRestartNudgeCondition clusterv1.ConditionType = "KubeletRestartNudge"

// TalosVersionReadyCondition reports the claim-time Talos upgrade state. It is
// only set when DesiredTalosVersion is non-empty (opt-out keeps the condition
// list clean). Reasons: Upgrading (Reset issued or Upgrade RPC in flight),
// Upgraded (Version RPC reports the desired tag, upgrade complete),
// UpgradeFailed (post-upgrade probe exhausted retries), VersionProbeFailed
// (pre-upgrade probe exhausted retries), InvalidImageRef (DesiredTalosVersion
// has no parseable tag). Never True while the machine is mid-upgrade; Ready
// stays false throughout and is driven by the normal adoption gate.
const TalosVersionReadyCondition clusterv1.ConditionType = "TalosVersionReady"

// nodeLinkRetriggerSelfFilter is a watch predicate that drops Update events
// whose only change is the nodeLinkRetriggerAnnotation. The ByotMachine
// reconciler bumps that annotation to retrigger the owning CAPI Machine's
// node-link, then requeues after requeueAfterNodeLink.
type nodeLinkRetriggerSelfFilter struct{}

func (nodeLinkRetriggerSelfFilter) Create(event.CreateEvent) bool   { return true }
func (nodeLinkRetriggerSelfFilter) Delete(event.DeleteEvent) bool   { return true }
func (nodeLinkRetriggerSelfFilter) Generic(event.GenericEvent) bool { return true }

// Update drops the event when the only change between old and new is the
// nodeLinkRetriggerAnnotation value.
func (nodeLinkRetriggerSelfFilter) Update(evt event.UpdateEvent) bool {
	if evt.ObjectOld == nil || evt.ObjectNew == nil {
		return true
	}

	oldAnn := withoutNodeLinkRetrigger(evt.ObjectOld.GetAnnotations())
	newAnn := withoutNodeLinkRetrigger(evt.ObjectNew.GetAnnotations())

	return !maps.Equal(oldAnn, newAnn) ||
		evt.ObjectOld.GetGeneration() != evt.ObjectNew.GetGeneration()
}

// withoutNodeLinkRetrigger returns a copy of annotations with the
// nodeLinkRetriggerAnnotation key removed.
func withoutNodeLinkRetrigger(annotations map[string]string) map[string]string {
	if len(annotations) == 0 {
		return map[string]string{}
	}

	filtered := make(map[string]string, len(annotations))
	for k, v := range annotations {
		if k == nodeLinkRetriggerAnnotation {
			continue
		}

		filtered[k] = v
	}

	return filtered
}

// ByotMachineReconciler reconciles a ByotMachine object.
type ByotMachineReconciler struct {
	Client ctrlclient.Client
	Scheme *runtime.Scheme

	// ClusterCache provides workload-cluster clients used to patch the
	// downstream Node providerID. nil when no cache is wired (unit tests); set
	// via SetClusterCache from Kommodity.
	ClusterCache clustercache.ClusterCache

	// getWorkloadClient is a seam over ClusterCache.GetClient, injectable in
	// tests. updateNodeProviderID skips when it is nil and falls back to the
	// nodeLinkRetriggerAnnotation path in ensureNodeLinked.
	getWorkloadClient func(ctx context.Context, cluster ctrlclient.ObjectKey) (ctrlclient.Client, error)

	// upgrade seams, injectable in tests; default to the real helpers.
	// See ensureTalosVersion. The pre-upgrade and in-flight probes run over
	// the cluster talosconfig (an adopted host no longer answers the
	// maintenance client).
	versionProbeAuthenticated func(ctx context.Context, publicIP string, talosConfig []byte) (string, error)
	upgradeMachine           func(ctx context.Context, publicIP string, talosConfig []byte, image string) error
}

// NewByotMachineReconciler creates a new ByotMachineReconciler.
func NewByotMachineReconciler(client ctrlclient.Client) *ByotMachineReconciler {
	return &ByotMachineReconciler{
		Client: client,
		Scheme: client.Scheme(),

		versionProbeAuthenticated:    versionProbeAuthenticated,
		upgradeMachine:              upgradeMachine,
	}
}

// SetClusterCache wires the ClusterCache and derives the workload-client
// seam used by updateNodeProviderID. Call before SetupWithManager.
func (r *ByotMachineReconciler) SetClusterCache(cache clustercache.ClusterCache) {
	r.ClusterCache = cache
	r.getWorkloadClient = cache.GetClient
}

// SetupWithManager sets up the controller with the Manager.
func (r *ByotMachineReconciler) SetupWithManager(
	manager ctrl.Manager,
	options ctrlcontroller.Options,
) error {
	err := ctrl.NewControllerManagedBy(manager).
		For(&infrav1.ByotMachine{}, builder.WithPredicates(nodeLinkRetriggerSelfFilter{})).
		WithOptions(options).
		Complete(r)
	if err != nil {
		return fmt.Errorf("failed to build ByotMachine controller: %w", err)
	}

	return nil
}

// +kubebuilder:rbac:groups=infrastructure.cluster.x-k8s.io,resources=byotmachines,verbs=get;list;watch;update;patch
// +kubebuilder:rbac:groups=infrastructure.cluster.x-k8s.io,resources=byotmachines,verbs=create;delete
// +kubebuilder:rbac:groups=infrastructure.cluster.x-k8s.io,resources=byotmachines/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=infrastructure.cluster.x-k8s.io,resources=byotmachines/finalizers,verbs=update
// +kubebuilder:rbac:groups=infrastructure.cluster.x-k8s.io,resources=byothosts,verbs=get;list;watch;update
// +kubebuilder:rbac:groups=infrastructure.cluster.x-k8s.io,resources=byothosts/status,verbs=update;patch
// +kubebuilder:rbac:groups=infrastructure.cluster.x-k8s.io,resources=byothosts/finalizers,verbs=update
// +kubebuilder:rbac:groups=cluster.x-k8s.io,resources=machines;machines/status,verbs=get;list;watch
// +kubebuilder:rbac:groups="",resources=secrets,verbs=get;list;watch

// Reconcile adopts the Talos machine referenced by the ByotMachine.
func (r *ByotMachineReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	byotMachine := &infrav1.ByotMachine{}

	err := r.Client.Get(ctx, req.NamespacedName, byotMachine)
	if err != nil {
		if apierrors.IsNotFound(err) {
			return ctrl.Result{}, nil
		}

		return ctrl.Result{}, fmt.Errorf("failed to get ByotMachine %s: %w", req.NamespacedName, err)
	}

	if !byotMachine.DeletionTimestamp.IsZero() {
		return r.reconcileDelete(ctx, byotMachine)
	}

	_, err = finalizers.EnsureFinalizer(ctx, r.Client, byotMachine, byotMachineFinalizer)
	if err != nil {
		return ctrl.Result{}, fmt.Errorf("failed to add finalizer to ByotMachine %s: %w", req.NamespacedName, err)
	}

	result, err := r.adopt(ctx, byotMachine)
	if err != nil {
		return result, fmt.Errorf("failed to adopt ByotMachine %s: %w", req.NamespacedName, err)
	}

	return result, nil
}

func (r *ByotMachineReconciler) adopt(ctx context.Context, byotMachine *infrav1.ByotMachine) (ctrl.Result, error) {
	patchHelper, err := patch.NewHelper(byotMachine, r.Client)
	if err != nil {
		return ctrl.Result{}, fmt.Errorf("failed to create patch helper: %w", err)
	}

	machine, machineConfig, wait, err := r.adoptionInputs(ctx, byotMachine)
	if err != nil {
		return ctrl.Result{}, err
	}

	if wait != nil {
		return *wait, nil
	}

	// Claim a ByotHost before adopting. The host's public IP is the adoption
	// target; claiming is idempotent once resolvedHost is set.
	claimResult, handled, err := r.claimHost(ctx, byotMachine, patchHelper)
	if err != nil {
		return ctrl.Result{}, err
	}

	if handled {
		return claimResult, nil
	}

	configHash := sha256Hex(machineConfig)

	if configUnchanged(byotMachine, configHash) {
		return r.reconcileAdopted(ctx, patchHelper, byotMachine, machine)
	}

	return r.applyAndMarkAdopted(ctx, patchHelper, machine, byotMachine, machineConfig, configHash)
}

// reconcileAdopted drives the steady-state path for an already-adopted
// ByotMachine: link the workload Node, then run the post-adoption Talos
// upgrade (opt-in via DesiredTalosVersion). The upgrade runs after the node is
// linked, over the cluster talosconfig (Admin), since a maintenance client
// cannot call Upgrade (Talos authz). Returns handled=true while the upgrade
// is in flight (InFlight) or stopped on failure.
func (r *ByotMachineReconciler) reconcileAdopted(
	ctx context.Context,
	patchHelper *patch.Helper,
	byotMachine *infrav1.ByotMachine,
	machine *clusterv1.Machine,
) (ctrl.Result, error) {
	linkResult, err := r.linkNode(ctx, patchHelper, byotMachine, machine)
	if err != nil {
		return linkResult, err
	}

	if linkResult.Requeue || linkResult.RequeueAfter > 0 {
		return linkResult, nil
	}

	upgradeResult, handled, err := r.ensureTalosVersion(ctx, patchHelper, byotMachine, machine)
	if err != nil {
		return upgradeResult, err
	}

	if handled {
		return upgradeResult, nil
	}

	return linkResult, nil
}

// resolveApplyAuth picks the talosconfig to authenticate the configuration
// apply with, and returns nil for machines in maintenance mode. A non-nil
// result signals the reconcile should requeue while a needed secret becomes
// available. bundleMatch is true when the machine already carries this
// cluster's PKI bundle.
//
// For machines not yet adopted, it first runs the join preflight, which
// determines whether the machine is maintenance-mode, carries this cluster's
// PKI bundle, or carries a foreign bundle (in which case adoption fails).
func (r *ByotMachineReconciler) resolveApplyAuth(
	ctx context.Context,
	patchHelper *patch.Helper,
	machine *clusterv1.Machine,
	byotMachine *infrav1.ByotMachine,
) ([]byte, bool, *ctrl.Result, error) {
	// Re-application on an already-adopted machine: use the cluster's own
	// talosconfig (the machine carries our PKI since its first apply).
	if byotMachine.Status.Ready {
		talosConfig, result, err := r.awaitClusterTalosConfig(ctx, machine.Spec.ClusterName, byotMachine)

		return talosConfig, true, result, err
	}

	return r.preflightJoin(ctx, patchHelper, machine, byotMachine)
}

// awaitClusterTalosConfig loads the cluster's own talosconfig, requeueing
// while the bootstrap provider has not generated it yet.
func (r *ByotMachineReconciler) awaitClusterTalosConfig(
	ctx context.Context,
	clusterName string,
	byotMachine *infrav1.ByotMachine,
) ([]byte, *ctrl.Result, error) {
	logger := log.FromContext(ctx)

	talosConfig, err := r.clusterTalosConfig(ctx, clusterName, byotMachine.Namespace)
	if errors.Is(err, ErrClusterTalosConfigNotReady) {
		logger.Info("Waiting for cluster talosconfig", "byotMachine", byotMachine.Name)

		return nil, &ctrl.Result{RequeueAfter: requeueAfterBootstrap}, nil
	}

	return talosConfig, nil, err
}

// preflightJoin determines whether a machine being adopted for the first time
// is in maintenance mode or carries this cluster's PKI bundle, and returns the
// matching authentication. A machine that answers the Talos API with a foreign
// bundle fails the preflight instead of being silently misconfigured (see
// PLA-6479).
func (r *ByotMachineReconciler) preflightJoin(
	ctx context.Context,
	patchHelper *patch.Helper,
	machine *clusterv1.Machine,
	byotMachine *infrav1.ByotMachine,
) ([]byte, bool, *ctrl.Result, error) {
	publicIP := byotMachine.Status.ResolvedPublicIP

	if probeMaintenance(ctx, publicIP) {
		conditions.Set(byotMachine, &clusterv1.Condition{
			Type:   JoinPreflightCondition,
			Status: corev1.ConditionTrue,
			Reason: "MaintenanceMode",
		})

		return nil, false, nil, nil
	}

	talosConfig, err := r.clusterTalosConfig(ctx, machine.Spec.ClusterName, byotMachine.Namespace)
	if errors.Is(err, ErrClusterTalosConfigNotReady) {
		logger := log.FromContext(ctx)
		logger.Info("Waiting for cluster talosconfig", "byotMachine", byotMachine.Name)

		return nil, false, &ctrl.Result{RequeueAfter: requeueAfterBootstrap}, nil
	}

	if err != nil {
		return nil, false, nil, err
	}

	if probeAuthenticated(ctx, publicIP, talosConfig) {
		conditions.Set(byotMachine, &clusterv1.Condition{
			Type:   JoinPreflightCondition,
			Status: corev1.ConditionTrue,
			Reason: "BundleMatch",
		})

		return talosConfig, true, nil, nil
	}

	talosConfig, result, err := r.preflightForeignMachine(ctx, patchHelper, byotMachine)

	return talosConfig, false, result, err
}

// ensureTalosVersion drives the post-adoption Talos upgrade state machine.
// It is opt-in (only runs when DesiredTalosVersion is set) and runs after the
// machine is adopted (Ready=true): the upgrade uses the cluster talosconfig
// (mTLS, Admin) because a maintenance-mode client is Reader-only and cannot
// call Upgrade (Talos authz). Returns handled=true while the upgrade is in
// flight (InFlight) or stopped on failure, so the caller returns its result
// instead of ending the reconcile. When opt-out or complete (version matches),
// returns handled=false so the reconcile ends cleanly.
//
// preserve=true carries the just-applied machineconfig across the upgrade
// reboot so the node rejoins the cluster on the new version without
// re-adoption. force=false: the predicate excludes same-version calls. No
// semver guard — the state machine treats any tag mismatch as an upgrade,
// but Talos's Upgrade RPC with force=false silently no-ops a downgrade
// (install sequence runs 0 phases, no reboot, no error), so a downgrade
// desired version leaves the host on its current version and the InFlight
// poll never matches. Downgrade support would require force=true (a separate
// opt-in). The pre-upgrade and in-flight Version probes both run over the
// cluster talosconfig (the host carries the cluster PKI bundle once adopted).
func (r *ByotMachineReconciler) ensureTalosVersion(
	ctx context.Context,
	patchHelper *patch.Helper,
	byotMachine *infrav1.ByotMachine,
	machine *clusterv1.Machine,
) (ctrl.Result, bool, error) {
	if byotMachine.Spec.DesiredTalosVersion == nil || *byotMachine.Spec.DesiredTalosVersion == "" {
		return ctrl.Result{}, false, nil
	}

	// Post-adoption only: the upgrade needs the cluster talosconfig, which is
	// only usable once the bootstrap config is applied and the host carries
	// the cluster PKI bundle.
	if !byotMachine.Status.Ready {
		return ctrl.Result{}, false, nil
	}

	desired := *byotMachine.Spec.DesiredTalosVersion
	desiredTag := installerTag(desired)

	// Retrigger after a stopped failure: an operator edit bumps generation,
	// so a Failed state whose attempt generation is stale is cleared and the
	// state machine restarts from the top.
	_, err := r.retriggerStaleUpgradeFailure(ctx, patchHelper, byotMachine)
	if err != nil {
		return ctrl.Result{}, true, err
	}

	switch byotMachine.Status.UpgradeState {
	case "":
		// The tag is only validated at the start of the upgrade; once past it
		// (InFlight) the ref was already validated.
		if desiredTag == "" || desiredTag == desired {
			return r.markInvalidImageRef(ctx, patchHelper, byotMachine, desired)
		}

		return r.upgradeProbeAndIssue(ctx, patchHelper, byotMachine, machine, desired, desiredTag)
	case infrav1.UpgradeStateInFlight:
		return r.upgradeInFlight(ctx, patchHelper, byotMachine, machine, desiredTag)
	case infrav1.UpgradeStateFailed:
		return ctrl.Result{}, true, nil // current-generation failure: stopped
	}

	return ctrl.Result{}, true, nil
}

// retriggerStaleUpgradeFailure clears a Failed upgrade state when the
// operator has edited DesiredTalosVersion since the attempt (generation
// bumped), so the state machine restarts. Returns retriggered=true when it
// cleared the state.
func (r *ByotMachineReconciler) retriggerStaleUpgradeFailure(
	ctx context.Context,
	patchHelper *patch.Helper,
	byotMachine *infrav1.ByotMachine,
) (bool, error) {
	if byotMachine.Status.UpgradeState != infrav1.UpgradeStateFailed ||
		byotMachine.Generation == byotMachine.Status.UpgradeAttemptGeneration {
		return false, nil
	}

	log.FromContext(ctx).Info("Retriggering Talos upgrade after failure", "byotMachine", byotMachine.Name)

	byotMachine.Status.UpgradeState = ""
	byotMachine.Status.UpgradeProbeFailures = 0

	err := patchHelper.Patch(ctx, byotMachine)
	if err != nil {
		return false, fmt.Errorf("failed to patch ByotMachine on upgrade retrigger: %w", err)
	}

	return true, nil
}

// markInvalidImageRef records that DesiredTalosVersion has no parseable tag
// and stops the upgrade (no requeue).
func (r *ByotMachineReconciler) markInvalidImageRef(
	ctx context.Context,
	patchHelper *patch.Helper,
	byotMachine *infrav1.ByotMachine,
	desired string,
) (ctrl.Result, bool, error) {
	conditions.MarkFalse(byotMachine, TalosVersionReadyCondition, "InvalidImageRef",
		clusterv1.ConditionSeverityError, "DesiredTalosVersion %q has no parseable tag", desired)

	byotMachine.Status.UpgradeAttemptGeneration = byotMachine.Generation

	err := patchHelper.Patch(ctx, byotMachine)
	if err != nil {
		return ctrl.Result{}, true, fmt.Errorf("failed to patch ByotMachine on invalid image ref: %w", err)
	}

	return ctrl.Result{}, true, nil
}

// recordUpgradeProbeFailure records a consecutive Version probe failure during
// the upgrade. When the threshold is reached it moves to Failed, marks the
// condition, and returns stop=true (no requeue). Otherwise it patches the
// incremented counter and returns a requeue.
func (r *ByotMachineReconciler) recordUpgradeProbeFailure(
	ctx context.Context,
	patchHelper *patch.Helper,
	byotMachine *infrav1.ByotMachine,
	threshold int32,
	reason string,
	probeErr error,
) (ctrl.Result, bool, error) {
	byotMachine.Status.UpgradeProbeFailures++

	if byotMachine.Status.UpgradeProbeFailures < threshold {
		err := patchHelper.Patch(ctx, byotMachine)
		if err != nil {
			return ctrl.Result{}, true, fmt.Errorf("failed to patch ByotMachine on upgrade probe retry: %w", err)
		}

		return ctrl.Result{RequeueAfter: requeueAfterUpgrade}, true, nil
	}

	byotMachine.Status.UpgradeState = infrav1.UpgradeStateFailed
	byotMachine.Status.UpgradeAttemptGeneration = byotMachine.Generation

	conditions.MarkFalse(byotMachine, TalosVersionReadyCondition, reason,
		clusterv1.ConditionSeverityWarning, "probe failed %d times: %s",
		byotMachine.Status.UpgradeProbeFailures, probeErr.Error())

	err := patchHelper.Patch(ctx, byotMachine)
	if err != nil {
		return ctrl.Result{}, true, fmt.Errorf("failed to patch ByotMachine on upgrade failure: %w", err)
	}

	log.FromContext(ctx).Info("Talos upgrade probe exhausted retries",
		"byotMachine", byotMachine.Name, "publicIP", byotMachine.Status.ResolvedPublicIP)

	return ctrl.Result{}, true, nil
}

// upgradeProbeAndIssue runs the pre-upgrade Version probe over the cluster
// talosconfig. On success it sets CurrentTalosVersion and either marks the
// upgrade complete (version already matches) or issues the Upgrade RPC and
// moves to InFlight. Probe failures accumulate up to versionProbeThreshold
// before the controller stops with VersionProbeFailed.
func (r *ByotMachineReconciler) upgradeProbeAndIssue(
	ctx context.Context,
	patchHelper *patch.Helper,
	byotMachine *infrav1.ByotMachine,
	machine *clusterv1.Machine,
	desired string,
	desiredTag string,
) (ctrl.Result, bool, error) {
	publicIP := byotMachine.Status.ResolvedPublicIP

	talosConfig, result, err := r.awaitClusterTalosConfig(ctx, machine.Spec.ClusterName, byotMachine)
	if err != nil {
		return ctrl.Result{}, true, err
	}

	if result != nil {
		return *result, true, nil
	}

	tag, err := r.versionProbeAuthenticated(ctx, publicIP, talosConfig)
	if err != nil {
		return r.recordUpgradeProbeFailure(ctx, patchHelper, byotMachine, versionProbeThreshold, "VersionProbeFailed", err)
	}

	byotMachine.Status.CurrentTalosVersion = tag
	byotMachine.Status.UpgradeProbeFailures = 0

	if tag == desiredTag {
		return r.markUpgradeComplete(ctx, patchHelper, byotMachine)
	}

	// Version mismatch: Upgrade over the cluster talosconfig (preserve=true
	// carries the just-applied machineconfig across the reboot).
	// Set InFlight before issuing the RPC so a crash between the patch and
	// the call is recoverable (the InFlight poll path re-probes and either
	// completes or, still old, requeues). If the RPC itself fails (e.g. Talos
	// refuses the upgrade on an etcd-quorum guard for a control-plane node),
	// revert to "" so the next reconcile re-issues instead of polling a
	// version that never changed.
	byotMachine.Status.UpgradeState = infrav1.UpgradeStateInFlight
	byotMachine.Status.UpgradeAttemptGeneration = byotMachine.Generation

	conditions.MarkFalse(byotMachine, TalosVersionReadyCondition, "Upgrading",
		clusterv1.ConditionSeverityInfo, "upgrading host to %s", desired)

	err = patchHelper.Patch(ctx, byotMachine)
	if err != nil {
		return ctrl.Result{}, true, fmt.Errorf("failed to patch ByotMachine before upgrade: %w", err)
	}

	err = r.upgradeMachine(ctx, publicIP, talosConfig, desired)
	if err != nil {
		return r.revertInFlightOnError(ctx, byotMachine, err)
	}

	log.FromContext(ctx).Info("Talos upgrade issued",
		"byotMachine", byotMachine.Name, "publicIP", publicIP, "desired", desired)

	return ctrl.Result{RequeueAfter: requeueAfterUpgrade}, true, nil
}

// revertInFlightOnError clears InFlight after a failed Upgrade RPC. A fresh
// patch helper snapshots the just-patched InFlight state as its base, so the
// revert to "" produces a real diff (the original helper's base still had
// InFlight unset and would no-op). Without this, the InFlight poll path would
// poll a version that never changed and never re-issue.
func (r *ByotMachineReconciler) revertInFlightOnError(
	ctx context.Context,
	byotMachine *infrav1.ByotMachine,
	upgradeErr error,
) (ctrl.Result, bool, error) {
	revertHelper, revertErr := patch.NewHelper(byotMachine, r.Client)
	if revertErr != nil {
		return ctrl.Result{}, true, fmt.Errorf("failed to upgrade machine: %w (revert helper: %w)", upgradeErr, revertErr)
	}

	byotMachine.Status.UpgradeState = ""

	revertErr = revertHelper.Patch(ctx, byotMachine)
	if revertErr != nil {
		return ctrl.Result{}, true, fmt.Errorf("failed to upgrade machine: %w (revert InFlight failed: %w)",
			upgradeErr, revertErr)
	}

	return ctrl.Result{}, true, fmt.Errorf("failed to upgrade machine: %w", upgradeErr)
}

// upgradeInFlight polls the Version RPC (cluster talosconfig) until it reports
// the desired tag (upgrade complete → done) or exhausts upgradeThreshold
// retries (UpgradeFailed, stop). A probe that succeeds with a different tag
// keeps InFlight and requeues.
func (r *ByotMachineReconciler) upgradeInFlight(
	ctx context.Context,
	patchHelper *patch.Helper,
	byotMachine *infrav1.ByotMachine,
	machine *clusterv1.Machine,
	desiredTag string,
) (ctrl.Result, bool, error) {
	publicIP := byotMachine.Status.ResolvedPublicIP

	talosConfig, result, err := r.awaitClusterTalosConfig(ctx, machine.Spec.ClusterName, byotMachine)
	if err != nil {
		return ctrl.Result{}, true, err
	}

	if result != nil {
		return *result, true, nil
	}

	tag, err := r.versionProbeAuthenticated(ctx, publicIP, talosConfig)
	if err != nil {
		return r.recordUpgradeProbeFailure(ctx, patchHelper, byotMachine, upgradeThreshold, "UpgradeFailed", err)
	}

	byotMachine.Status.CurrentTalosVersion = tag
	byotMachine.Status.UpgradeProbeFailures = 0

	if tag != desiredTag {
		err = patchHelper.Patch(ctx, byotMachine)
		if err != nil {
			return ctrl.Result{}, true, fmt.Errorf("failed to patch ByotMachine on upgrade poll: %w", err)
		}

		return ctrl.Result{RequeueAfter: requeueAfterUpgrade}, true, nil
	}

	return r.markUpgradeComplete(ctx, patchHelper, byotMachine)
}

// markUpgradeComplete clears the upgrade state and marks TalosVersionReady
// True/Upgraded so the reconcile ends cleanly (the node is adopted and on the
// desired version).
func (r *ByotMachineReconciler) markUpgradeComplete(
	ctx context.Context,
	patchHelper *patch.Helper,
	byotMachine *infrav1.ByotMachine,
) (ctrl.Result, bool, error) {
	byotMachine.Status.UpgradeState = ""

	conditions.Set(byotMachine, &clusterv1.Condition{
		Type: TalosVersionReadyCondition, Status: corev1.ConditionTrue, Reason: "Upgraded",
	})

	err := patchHelper.Patch(ctx, byotMachine)
	if err != nil {
		return ctrl.Result{}, true, fmt.Errorf("failed to patch ByotMachine on upgrade complete: %w", err)
	}

	log.FromContext(ctx).Info("Talos upgrade complete",
		"byotMachine", byotMachine.Name, "publicIP", byotMachine.Status.ResolvedPublicIP,
		"version", byotMachine.Status.CurrentTalosVersion)

	return ctrl.Result{}, false, nil
}

func (r *ByotMachineReconciler) applyAndMarkAdopted(
	ctx context.Context,
	patchHelper *patch.Helper,
	machine *clusterv1.Machine,
	byotMachine *infrav1.ByotMachine,
	machineConfig []byte,
	configHash string,
) (ctrl.Result, error) {
	logger := log.FromContext(ctx)

	talosConfig, bundleMatch, result, err := r.resolveApplyAuth(ctx, patchHelper, machine, byotMachine)
	if err != nil {
		return ctrl.Result{}, err
	}

	if result != nil {
		return *result, nil
	}

	wasReady := byotMachine.Status.Ready

	err = applyMachineConfig(ctx, byotMachine.Status.ResolvedPublicIP, machineConfig, talosConfig)
	if err != nil {
		return ctrl.Result{}, r.recordApplyFailure(ctx, patchHelper, byotMachine, err)
	}

	// Best-effort kubelet re-registration nudge for a bundleMatch re-adopt: the
	// machine keeps its config and datastore, the Node may have been deleted by
	// Cluster API, and the kubelet only re-registers it on restart. It runs
	// solely when the machine was adopted via an authenticated apply (bundleMatch)
	// on a not-yet-ready ByotMachine: a re-apply on an already-ready machine needs
	// no restart, and a fresh maintenance-mode adoption reboots so the kubelet
	// starts on boot.
	//
	// The nudge only restarts a kubelet that is already Running.
	//
	// Its failure never reverts a successful adoption: the configuration
	// apply already succeeded and the kubelet (re)starts on boot. A
	// transient failure (machine rebooting after its first apply, service
	// not yet defined) is recorded as a warning and self-heals when the
	// kubelet comes up.
	nudgeKubeletAfterReadopt(ctx, byotMachine, talosConfig, bundleMatch, wasReady, serviceRunning, restartService)

	markAdopted(byotMachine, configHash)

	err = patchHelper.Patch(ctx, byotMachine)
	if err != nil {
		return ctrl.Result{}, fmt.Errorf("failed to patch ByotMachine: %w", err)
	}

	logger.Info("Machine adopted", "byotMachine", byotMachine.Name, "publicIP", byotMachine.Status.ResolvedPublicIP)

	return r.linkNode(ctx, patchHelper, byotMachine, machine)
}

// linkNode drives the Machine<->Node linkage for an adopted machine: first
// patch the workload Node's providerID (byot has no CCM, so the controller
// owns it), then retrigger the owning CAPI Machine's node-link reconciliation
// until status.nodeRef is set. updateNodeProviderID runs once (gated by
// status.nodeUpdated); ensureNodeLinked keeps retriggerring until the link
// completes. A requeue from either step short-circuits the other, which is
// fine since both re-run on the next reconcile.
func (r *ByotMachineReconciler) linkNode(
	ctx context.Context,
	patchHelper *patch.Helper,
	byotMachine *infrav1.ByotMachine,
	machine *clusterv1.Machine,
) (ctrl.Result, error) {
	result, err := r.updateNodeProviderID(ctx, patchHelper, byotMachine, machine)
	if err != nil {
		return result, err
	}

	if result.Requeue || result.RequeueAfter > 0 {
		return result, nil
	}

	return r.ensureNodeLinked(ctx, patchHelper, byotMachine, machine)
}

// errWorkloadNodePending signals the workload Node is not registered yet;
// the kubelet registers it on boot. updateNodeProviderID requeues on it.
var errWorkloadNodePending = errors.New("workload node not registered")

// updateNodeProviderID patches the workload cluster Node's spec.providerID to
// byot://<resolvedPublicIP> so CAPI's Machine controller can link the Machine
// to its Node. byot has no cloud-controller-manager, so unlike cloud providers
// the controller owns the Machine<->Node providerID linkage: the kubelet
// reports an empty providerID (the host-registry model resolves the IP at
// claim time, so neither the chart nor CABPT can bake it into the config), so
// CAPI's Machine.spec.providerID <-> Node.spec.providerID match never fires
// and status.nodeRef is never set. Mirrors the kubevirt provider
// (KubevirtMachineReconciler.updateNodeProviderID). Gated by
// status.nodeUpdated so it runs once. When no ClusterCache is wired it is a
// no-op and ensureNodeLinked's retrigger annotation is the fallback.
func (r *ByotMachineReconciler) updateNodeProviderID(
	ctx context.Context,
	patchHelper *patch.Helper,
	byotMachine *infrav1.ByotMachine,
	machine *clusterv1.Machine,
) (ctrl.Result, error) {
	if byotMachine.Status.NodeUpdated || byotMachine.Spec.ProviderID == nil {
		return ctrl.Result{}, nil
	}

	if r.getWorkloadClient == nil {
		// No ClusterCache wired (unit tests, or provider run standalone).
		// ensureNodeLinked's retrigger annotation is the fallback.
		return ctrl.Result{}, nil
	}

	clusterKey := ctrlclient.ObjectKey{
		Namespace: byotMachine.Namespace,
		Name:      machine.Spec.ClusterName,
	}

	workloadClient, err := r.getWorkloadClient(ctx, clusterKey)

	if errors.Is(err, clustercache.ErrClusterNotConnected) {
		// Workload API not up yet (control-plane bootstrap race). Requeue;
		// ensureNodeLinked's retrigger also compensates.
		return ctrl.Result{RequeueAfter: requeueAfterNodeLink}, nil
	}

	if err != nil {
		return ctrl.Result{}, fmt.Errorf("failed to get workload cluster client for %s: %w", clusterKey, err)
	}

	_, pErr := r.patchWorkloadNode(ctx, workloadClient, byotMachine, *byotMachine.Spec.ProviderID)
	if pErr != nil {
		if errors.Is(pErr, errWorkloadNodePending) {
			// Node not registered yet; the kubelet registers on boot. Requeue.
			return ctrl.Result{RequeueAfter: requeueAfterNodeLink}, nil
		}

		return ctrl.Result{}, pErr
	}

	byotMachine.Status.NodeUpdated = true

	err = patchHelper.Patch(ctx, byotMachine)
	if err != nil {
		return ctrl.Result{}, fmt.Errorf("failed to patch ByotMachine after Node providerID update: %w", err)
	}

	log.FromContext(ctx).Info("Patched workload Node providerID",
		"byotMachine", byotMachine.Name, "machine", machine.Name)

	return ctrl.Result{}, nil
}

// patchWorkloadNode gets the workload Node named after the ByotMachine
// (CABPT sets hostname.source=InfrastructureName, so the Node name equals
// the infrastructureRef name == ByotMachine.Name) and patches its
// spec.providerID when it does not already match. It returns alreadySet=true
// when the Node already carries the providerID (a prior run), so the caller
// marks status.nodeUpdated without a redundant patch. errWorkloadNodePending
// means the Node is not registered yet.
func (r *ByotMachineReconciler) patchWorkloadNode(
	ctx context.Context,
	workloadClient ctrlclient.Client,
	byotMachine *infrav1.ByotMachine,
	providerID string,
) (bool, error) {
	node := &corev1.Node{}

	err := workloadClient.Get(ctx, ctrlclient.ObjectKey{Name: byotMachine.Name}, node)
	if err != nil {
		if apierrors.IsNotFound(err) {
			return false, errWorkloadNodePending
		}

		return false, fmt.Errorf("failed to get workload Node %s: %w", byotMachine.Name, err)
	}

	if node.Spec.ProviderID == providerID {
		return true, nil
	}

	// Patch the Node providerID. Usually a cloud-controller-manager does
	// this, but byot has no CCM.
	patchBytes := fmt.Sprintf(`{"spec":{"providerID":%q}}`, providerID)
	mergePatch := ctrlclient.RawPatch(types.MergePatchType, []byte(patchBytes))

	err = workloadClient.Patch(ctx, node, mergePatch)
	if err != nil {
		return false, fmt.Errorf("failed to patch workload Node %s providerID: %w", byotMachine.Name, err)
	}

	return false, nil
}

// ensureNodeLinked retriggers the owning CAPI Machine's node-link
// reconciliation until the Machine reports status.nodeRef. An adopted
// ByotMachine has spec.providerID set, and the CAPI Machine controller links
// the workload Node by matching that providerID. On the control plane the
// workload API is down while the Machine controller first reconciles, so its
// node watch can miss the control-plane Node registering and the Machine
// stalls on "Waiting for a node with matching ProviderID". Bumping
// nodeLinkRetriggerAnnotation changes the ByotMachine object, which the
// Machine controller watches, forcing a re-list of workload nodes until the
// link completes. Once nodeRef is set the annotation is cleared and the
// requeue stops.
func (r *ByotMachineReconciler) ensureNodeLinked(
	ctx context.Context,
	patchHelper *patch.Helper,
	byotMachine *infrav1.ByotMachine,
	machine *clusterv1.Machine,
) (ctrl.Result, error) {
	if !byotMachine.Status.Ready || byotMachine.Spec.ProviderID == nil {
		return ctrl.Result{}, nil
	}

	latest := &clusterv1.Machine{}

	err := r.Client.Get(ctx, ctrlclient.ObjectKeyFromObject(machine), latest)
	if err != nil {
		return ctrl.Result{}, fmt.Errorf("failed to get owner Machine %s: %w", machine.Name, err)
	}

	if latest.Status.NodeRef != nil {
		if _, ok := byotMachine.Annotations[nodeLinkRetriggerAnnotation]; ok {
			delete(byotMachine.Annotations, nodeLinkRetriggerAnnotation)

			err := patchHelper.Patch(ctx, byotMachine)
			if err != nil {
				return ctrl.Result{}, fmt.Errorf("failed to patch ByotMachine after clearing node-link annotation: %w", err)
			}
		}

		return ctrl.Result{}, nil
	}

	if byotMachine.Annotations == nil {
		byotMachine.Annotations = map[string]string{}
	}

	byotMachine.Annotations[nodeLinkRetriggerAnnotation] = strconv.FormatInt(time.Now().UnixNano(), 10)

	err = patchHelper.Patch(ctx, byotMachine)
	if err != nil {
		return ctrl.Result{}, fmt.Errorf("failed to patch ByotMachine with node-link retrigger: %w", err)
	}

	log.FromContext(ctx).Info("Retriggering Machine node-link",
		"byotMachine", byotMachine.Name, "machine", machine.Name)

	return ctrl.Result{RequeueAfter: requeueAfterNodeLink}, nil
}

// nudgeKubeletAfterReadopt restarts the kubelet so a Node deleted during a
// bundleMatch re-adopt re-registers, when the machine was re-adopted via an
// authenticated apply (bundleMatch) on a not-yet-ready ByotMachine. The restart
// is best-effort: its failure is recorded as a warning condition and never
// reverts the adoption, because the configuration apply already succeeded and
// the kubelet (re)starts on boot regardless. A fresh maintenance-mode adoption
// is excluded by the running probe: its kubelet starts on boot, and restarting
// a not-yet-running service would only record a spurious warning. running and
// restart are injected so the non-fatal path is unit-testable without a live
// Talos API.
func nudgeKubeletAfterReadopt(
	ctx context.Context,
	byotMachine *infrav1.ByotMachine,
	talosConfig []byte,
	bundleMatch bool,
	wasReady bool,
	running func(context.Context, string, []byte, string) (bool, error),
	restart func(context.Context, string, []byte, string) error,
) {
	logger := log.FromContext(ctx)

	if !bundleMatch || wasReady {
		return
	}

	// Only restart a kubelet that is already Running.
	isRunning, err := running(ctx, byotMachine.Status.ResolvedPublicIP, talosConfig, kubeletServiceID)
	if err != nil {
		// A probe failure is non-fatal: the kubelet registers on boot
		// regardless. Record nothing to avoid a spurious condition.
		logger.Info("Skipping kubelet restart nudge; service probe failed (non-fatal)",
			"byotMachine", byotMachine.Name,
			"publicIP", byotMachine.Status.ResolvedPublicIP,
			"error", err.Error())

		return
	}

	if !isRunning {
		logger.Info("Skipping kubelet restart nudge; kubelet not yet running (will register on boot)",
			"byotMachine", byotMachine.Name,
			"publicIP", byotMachine.Status.ResolvedPublicIP)

		return
	}

	err = restart(ctx, byotMachine.Status.ResolvedPublicIP, talosConfig, kubeletServiceID)
	if err != nil {
		conditions.MarkFalse(
			byotMachine,
			KubeletRestartNudgeCondition,
			"RestartFailed",
			clusterv1.ConditionSeverityWarning,
			"%s",
			err.Error(),
		)

		logger.Info("Kubelet restart nudge failed (non-fatal); kubelet registers on boot",
			"byotMachine", byotMachine.Name,
			"publicIP", byotMachine.Status.ResolvedPublicIP,
			"error", err.Error())

		return
	}

	conditions.MarkTrue(byotMachine, KubeletRestartNudgeCondition)

	logger.Info("Kubelet restarted after re-adoption",
		"byotMachine", byotMachine.Name,
		"publicIP", byotMachine.Status.ResolvedPublicIP)
}

// reconcileDelete releases the claimed ByotHost. Release always resets the
// host (STATE + EPHEMERAL) back to maintenance so it returns to the registry
// for re-claim; the ByotHost liveness loop flips Releasing → Available once
// maintenance answers. Deletion blocks until the reset is issued. A
// ByotMachine that never claimed a host is removed immediately.
func (r *ByotMachineReconciler) reconcileDelete(
	ctx context.Context,
	byotMachine *infrav1.ByotMachine,
) (ctrl.Result, error) {
	logger := log.FromContext(ctx)

	if !controllerutil.ContainsFinalizer(byotMachine, byotMachineFinalizer) {
		return ctrl.Result{}, nil
	}

	if byotMachine.Status.ResolvedHost != "" {
		err := r.releaseHost(ctx, byotMachine)
		if err != nil {
			logger.Info("Release reset failed, retrying",
				"byotMachine", byotMachine.Name,
				"byotHost", byotMachine.Status.ResolvedHost,
				"publicIP", byotMachine.Status.ResolvedPublicIP,
				"error", err.Error())

			return ctrl.Result{RequeueAfter: requeueAfterResetIssued}, nil
		}

		logger.Info("Host reset to maintenance and released",
			"byotMachine", byotMachine.Name,
			"byotHost", byotMachine.Status.ResolvedHost,
			"publicIP", byotMachine.Status.ResolvedPublicIP)
	} else {
		logger.Info("Machine released (no claimed host)",
			"byotMachine", byotMachine.Name)
	}

	if controllerutil.RemoveFinalizer(byotMachine, byotMachineFinalizer) {
		err := r.Client.Update(ctx, byotMachine)
		if err != nil {
			return ctrl.Result{}, fmt.Errorf("failed to remove finalizer from ByotMachine %s: %w", byotMachine.Name, err)
		}
	}

	return ctrl.Result{}, nil
}

// attemptReset tries each credential candidate (a nil candidate selects the
// insecure maintenance client) and returns the last error if all fail.
func attemptReset(ctx context.Context, candidates [][]byte, publicIP string) error {
	var lastErr error

	for _, candidate := range candidates {
		err := resetMachine(ctx, publicIP, candidate)
		if err == nil {
			return nil
		}

		lastErr = err
	}

	if lastErr != nil {
		return fmt.Errorf("failed to reset machine %s with any available credentials: %w", publicIP, lastErr)
	}

	return fmt.Errorf("%w: %s", ErrNoResetCredentials, publicIP)
}

// resetCredentialCandidates returns talosconfig candidates for the reset, in
// priority order, terminated by a nil entry which selects the insecure
// (maintenance) client.
func (r *ByotMachineReconciler) resetCredentialCandidates(
	ctx context.Context,
	byotMachine *infrav1.ByotMachine,
) ([][]byte, error) {
	candidates := [][]byte{}

	if byotMachine.Spec.TalosConfigSecretRef != nil {
		talosConfig, err := r.referencedTalosConfig(ctx, byotMachine.Spec.TalosConfigSecretRef.Name, byotMachine.Namespace)
		if err != nil && !errors.Is(err, ErrClusterTalosConfigNotReady) {
			return nil, fmt.Errorf("failed to load referenced talosconfig: %w", err)
		}

		if err == nil {
			candidates = append(candidates, talosConfig)
		}
	}

	clusterName := byotMachine.Labels[clusterNameLabel]
	if clusterName != "" {
		talosConfig, err := r.clusterTalosConfig(ctx, clusterName, byotMachine.Namespace)
		if err != nil && !errors.Is(err, ErrClusterTalosConfigNotReady) {
			return nil, fmt.Errorf("failed to load cluster talosconfig: %w", err)
		}

		if err == nil {
			candidates = append(candidates, talosConfig)
		}
	}

	return append(candidates, nil), nil
}

// adoptionInputs resolves the owner Machine and its bootstrap data. A non-nil
// wait result means one of them is not available yet; the caller should
// requeue with it.
func (r *ByotMachineReconciler) adoptionInputs(
	ctx context.Context,
	byotMachine *infrav1.ByotMachine,
) (*clusterv1.Machine, []byte, *ctrl.Result, error) {
	logger := log.FromContext(ctx)

	machine, err := util.GetOwnerMachine(ctx, r.Client, byotMachine.ObjectMeta)
	if err != nil {
		return nil, nil, nil, fmt.Errorf("failed to get owner Machine: %w", err)
	}

	if machine == nil {
		logger.Info("Waiting for Machine controller to set OwnerReference", "byotMachine", byotMachine.Name)

		return nil, nil, &ctrl.Result{RequeueAfter: requeueAfterBootstrap}, nil
	}

	machineConfig, err := r.bootstrapData(ctx, machine)
	if errors.Is(err, ErrBootstrapDataNotReady) {
		logger.Info("Waiting for bootstrap data", "byotMachine", byotMachine.Name, "machine", machine.Name)

		return nil, nil, &ctrl.Result{RequeueAfter: requeueAfterBootstrap}, nil
	}

	if err != nil {
		return nil, nil, nil, err
	}

	return machine, machineConfig, nil, nil
}

// recordApplyFailure marks the adoption condition false, persists it, and
// returns the apply error as the reconcile failure.
func (r *ByotMachineReconciler) recordApplyFailure(
	ctx context.Context,
	patchHelper *patch.Helper,
	byotMachine *infrav1.ByotMachine,
	applyErr error,
) error {
	conditions.MarkFalse(
		byotMachine,
		MachineAdoptedCondition,
		"ApplyFailed",
		clusterv1.ConditionSeverityWarning,
		"%s",
		applyErr.Error(),
	)

	err := patchHelper.Patch(ctx, byotMachine)
	if err != nil {
		return fmt.Errorf("failed to patch ByotMachine after apply failure: %w", err)
	}

	return applyErr
}

// markAdopted updates the ByotMachine spec and status after a successful
// machine configuration apply.
func markAdopted(byotMachine *infrav1.ByotMachine, configHash string) {
	providerID := infrav1.ProviderIDPrefix + byotMachine.Status.ResolvedPublicIP

	byotMachine.Spec.ProviderID = &providerID
	byotMachine.Status.Ready = true
	byotMachine.Status.LastAppliedConfigSHA = configHash
	byotMachine.Status.Addresses = []clusterv1.MachineAddress{
		{
			Type:    clusterv1.MachineExternalIP,
			Address: byotMachine.Status.ResolvedPublicIP,
		},
	}

	conditions.MarkTrue(byotMachine, MachineAdoptedCondition)
}

// configUnchanged reports whether the machine is already adopted with the
// same configuration that would be applied now.
func configUnchanged(byotMachine *infrav1.ByotMachine, configHash string) bool {
	return byotMachine.Status.Ready &&
		byotMachine.Spec.ProviderID != nil &&
		byotMachine.Status.LastAppliedConfigSHA == configHash
}

func sha256Hex(data []byte) string {
	sum := sha256.Sum256(data)

	return hex.EncodeToString(sum[:])
}

// bootstrapData reads the Talos machine configuration produced by the
// bootstrap provider for the given Machine.
func (r *ByotMachineReconciler) bootstrapData(
	ctx context.Context,
	machine *clusterv1.Machine,
) ([]byte, error) {
	if machine.Spec.Bootstrap.DataSecretName == nil {
		return nil, ErrBootstrapDataNotReady
	}

	secret := &corev1.Secret{}
	secretKey := ctrlclient.ObjectKey{
		Namespace: machine.Namespace,
		Name:      *machine.Spec.Bootstrap.DataSecretName,
	}

	err := r.Client.Get(ctx, secretKey, secret)
	if err != nil {
		if apierrors.IsNotFound(err) {
			return nil, ErrBootstrapDataNotReady
		}

		return nil, fmt.Errorf("failed to get bootstrap secret %s: %w", secretKey, err)
	}

	data, ok := secret.Data[bootstrapSecretDataKey]
	if !ok || len(data) == 0 {
		return nil, ErrBootstrapDataEmpty
	}

	return data, nil
}

// preflightForeignMachine handles a machine that is neither in maintenance
// mode nor accepting the cluster's own talosconfig. When the machine provably
// answers with a referenced foreign talosconfig, the join preflight fails
// with a bundle mismatch; otherwise the referenced config (if any) is used
// for the apply attempt, preserving the previous behavior for unreachable
// machines.
func (r *ByotMachineReconciler) preflightForeignMachine(
	ctx context.Context,
	patchHelper *patch.Helper,
	byotMachine *infrav1.ByotMachine,
) ([]byte, *ctrl.Result, error) {
	logger := log.FromContext(ctx)

	if byotMachine.Spec.TalosConfigSecretRef == nil {
		// Configured machine without credentials: treat it as a bundle
		// mismatch, it cannot be joined without resetting it first.
		return nil, nil, r.recordPreflightFailure(ctx, patchHelper, byotMachine, "NoCredentials", ErrJoinNoCredentials)
	}

	talosConfig, err := r.referencedTalosConfig(ctx, byotMachine.Spec.TalosConfigSecretRef.Name, byotMachine.Namespace)
	if errors.Is(err, ErrClusterTalosConfigNotReady) {
		logger.Info("Waiting for referenced talosconfig secret", "byotMachine", byotMachine.Name)

		return nil, &ctrl.Result{RequeueAfter: requeueAfterBootstrap}, nil
	}

	if err != nil {
		return nil, nil, err
	}

	if probeAuthenticated(ctx, byotMachine.Status.ResolvedPublicIP, talosConfig) {
		return nil, nil, r.recordPreflightFailure(ctx, patchHelper, byotMachine, "BundleMismatch", ErrJoinBundleMismatch)
	}

	return talosConfig, nil, nil
}

// recordPreflightFailure marks the join preflight condition false, persists
// it, and returns the preflight error as the reconcile failure.
func (r *ByotMachineReconciler) recordPreflightFailure(
	ctx context.Context,
	patchHelper *patch.Helper,
	byotMachine *infrav1.ByotMachine,
	reason string,
	preflightErr error,
) error {
	conditions.MarkFalse(
		byotMachine,
		JoinPreflightCondition,
		reason,
		clusterv1.ConditionSeverityError,
		"%s",
		preflightErr.Error(),
	)

	err := patchHelper.Patch(ctx, byotMachine)
	if err != nil {
		return fmt.Errorf("failed to patch ByotMachine after join preflight failure: %w", err)
	}

	return preflightErr
}

// clusterTalosConfig loads the talosconfig generated by the bootstrap provider
// for the given cluster (secret "<cluster>-talosconfig").
func (r *ByotMachineReconciler) clusterTalosConfig(
	ctx context.Context,
	clusterName string,
	namespace string,
) ([]byte, error) {
	return r.referencedTalosConfig(ctx, clusterName+clusterTalosConfigSecretSuffix, namespace)
}

// referencedTalosConfig loads a talosconfig document from a secret in the
// same namespace. A missing secret is treated as a not-ready state.
func (r *ByotMachineReconciler) referencedTalosConfig(
	ctx context.Context,
	secretName string,
	namespace string,
) ([]byte, error) {
	secret := &corev1.Secret{}
	secretKey := ctrlclient.ObjectKey{
		Namespace: namespace,
		Name:      secretName,
	}

	err := r.Client.Get(ctx, secretKey, secret)
	if err != nil {
		if apierrors.IsNotFound(err) {
			return nil, ErrClusterTalosConfigNotReady
		}

		return nil, fmt.Errorf("failed to get talosconfig secret %s: %w", secretKey, err)
	}

	data, ok := secret.Data[talosConfigSecretDataKey]
	if !ok || len(data) == 0 {
		return nil, ErrClusterTalosConfigNotReady
	}

	return data, nil
}
