package controller

import (
	"context"
	"fmt"
	"time"

	infrav1 "github.com/kommodity-io/cluster-api-provider-bringyourowntalos/api/v1alpha1"
	corev1 "k8s.io/api/core/v1"
	policyv1 "k8s.io/api/policy/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/fields"
	"k8s.io/apimachinery/pkg/types"
	clusterv1 "sigs.k8s.io/cluster-api/api/v1beta1"
	"sigs.k8s.io/cluster-api/util/kubeconfig"
	ctrlclient "sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/log"
)

const (
	// clusterKubeconfigSecretSuffix is the suffix of the secret holding the
	// workload cluster's admin kubeconfig, generated by CAPI.
	clusterKubeconfigSecretSuffix = "-kubeconfig" //nolint:gosec // File-name suffix, not a credential.

	// kubeconfigSecretDataKey is the key holding the kubeconfig document in
	// the cluster kubeconfig secret.
	kubeconfigSecretDataKey = "value"

	// nodeDrainTimeout bounds the best-effort drain+delete of a workload Node
	// during ByotMachine deletion. It caps the time spent evicting pods; on
	// timeout the Node is deleted anyway (force teardown).
	nodeDrainTimeout = 5 * time.Minute

	// drainPodPollInterval is the delay between two checks that all pods on a
	// draining Node have terminated.
	drainPodPollInterval = 5 * time.Second

	// mirrorPodAnnotation marks pods created by the kubelet from static
	// manifests; they cannot be evicted and are skipped (the kubelet removes
	// them when the Node is deleted).
	mirrorPodAnnotation = "kubernetes.io/config.mirror"

	// daemonSetController is the controller kind for DaemonSet-owned pods,
	// which are skipped during drain (they are pinned to the Node).
	daemonSetController = "DaemonSet"
)

// NodeCleanupCondition reports the outcome of the best-effort workload-Node
// drain+delete performed during ByotMachine deletion.
const NodeCleanupCondition clusterv1.ConditionType = "NodeCleanup"

// workloadClientsetBuilder builds a Kubernetes clientset from the workload
// cluster's kubeconfig bytes; a package-level indirection so the deletion
// path is unit-testable without a live workload API.
//
//nolint:gochecknoglobals // test seam: replaced in unit tests
var workloadClientsetBuilder = newWorkloadClientset

// cleanupWorkloadNode drains and deletes the workload-cluster Node backing
// byotMachine, using a client built from the cluster's kubeconfig secret
// (independent of the CAPI cluster cache, which is already torn down during
// Cluster deletion). It is best-effort: an unreachable workload API, a missing
// Node, or a drain timeout is recorded as a warning condition and never
// blocks the ByotMachine deletion. Returns nil on success or when there is
// nothing to clean.
func (r *ByotMachineReconciler) cleanupWorkloadNode(
	ctx context.Context,
	byotMachine *infrav1.ByotMachine,
	machine *clusterv1.Machine,
) error {
	logger := log.FromContext(ctx)

	clusterName := byotMachine.Labels[clusterNameLabel]
	if clusterName == "" && machine != nil {
		clusterName = machine.Spec.ClusterName
	}

	if clusterName == "" {
		return fmt.Errorf("%w: %s", ErrClusterNameUnresolved, byotMachine.Name)
	}

	kubeconfigBytes, err := kubeconfig.FromSecret(ctx, r.Client, ctrlclient.ObjectKey{
		Name:      clusterName,
		Namespace: byotMachine.Namespace,
	})
	if err != nil {
		return fmt.Errorf("failed to load workload kubeconfig for cluster %s: %w", clusterName, err)
	}

	clientset, err := workloadClientsetBuilder(kubeconfigBytes)
	if err != nil {
		return fmt.Errorf("failed to build workload clientset: %w", err)
	}

	nodeName, err := resolveWorkloadNodeName(ctx, clientset, machine, byotMachine)
	if err != nil {
		return err
	}

	if nodeName == "" {
		logger.Info("No workload Node to clean up", "byotMachine", byotMachine.Name)

		return nil
	}

	drainCtx, cancel := context.WithTimeout(ctx, nodeDrainTimeout)
	defer cancel()

	return drainAndDeleteNode(drainCtx, clientset, nodeName)
}

// resolveWorkloadNodeName finds the workload Node name for the ByotMachine,
// preferring the owning Machine's status.nodeRef, falling back to a providerID
// match (byot://<publicIP>) against the workload Nodes. Returns an empty name
// (no error) when no Node matches.
func resolveWorkloadNodeName(
	ctx context.Context,
	clientset workloadClientset,
	machine *clusterv1.Machine,
	byotMachine *infrav1.ByotMachine,
) (string, error) {
	if machine != nil && machine.Status.NodeRef != nil && machine.Status.NodeRef.Name != "" {
		return machine.Status.NodeRef.Name, nil
	}

	providerID := infrav1.ProviderIDPrefix + byotMachine.Spec.PublicIP

	nodes, err := clientset.Nodes().List(ctx, metav1.ListOptions{})
	if err != nil {
		return "", fmt.Errorf("failed to list workload nodes: %w", err)
	}

	return findNodeByProviderID(nodes.Items, providerID), nil
}

// findNodeByProviderID returns the name of the first Node whose spec.providerID
// matches, or an empty string when none matches.
func findNodeByProviderID(nodes []corev1.Node, providerID string) string {
	for _, node := range nodes {
		matched := node.Spec.ProviderID == providerID

		if matched {
			return node.Name
		}
	}

	return ""
}

// drainAndDeleteNode cordons the Node, evicts (or force-deletes) its pods, then
// deletes the Node object. DaemonSet pods and mirror pods are skipped; a pod
// eviction blocked by a PodDisruptionBudget falls back to a direct delete so
// teardown is not blocked. The context bounds the whole operation.
func drainAndDeleteNode(ctx context.Context, clientset workloadClientset, nodeName string) error {
	err := cordonNode(ctx, clientset, nodeName)
	if err != nil {
		return fmt.Errorf("failed to cordon node %s: %w", nodeName, err)
	}

	err = evictNodePods(ctx, clientset, nodeName)
	if err != nil {
		return fmt.Errorf("failed to drain pods from node %s: %w", nodeName, err)
	}

	err = clientset.Nodes().Delete(ctx, nodeName, metav1.DeleteOptions{})
	if err != nil {
		if apierrors.IsNotFound(err) {
			return nil
		}

		return fmt.Errorf("failed to delete node %s: %w", nodeName, err)
	}

	return nil
}

// cordonNode marks the Node unschedulable.
func cordonNode(ctx context.Context, clientset workloadClientset, nodeName string) error {
	patch := []byte(`{"spec":{"unschedulable":true}}`)
	_, err := clientset.Nodes().Patch(ctx, nodeName, types.MergePatchType, patch, metav1.PatchOptions{})

	return err
}

// evictNodePods evicts (or, on eviction rejection, force-deletes) every pod on
// the Node that is not a DaemonSet pod, a mirror pod, or already terminating.
// It then waits for the pods to disappear (bounded by the context).
func evictNodePods(ctx context.Context, clientset workloadClientset, nodeName string) error {
	pods, err := clientset.Pods(corev1.NamespaceAll).List(ctx, metav1.ListOptions{
		FieldSelector: fields.SelectorFromSet(fields.Set{"spec.nodeName": nodeName}).String(),
	})
	if err != nil {
		return fmt.Errorf("failed to list pods on node %s: %w", nodeName, err)
	}

	for _, pod := range pods.Items {
		if isDaemonSetPod(&pod) || isMirrorPod(&pod) || isTerminating(&pod) {
			continue
		}

		err := deleteOrEvictPod(ctx, clientset, &pod)
		if err != nil {
			return err
		}
	}

	return waitForPodsGone(ctx, clientset, nodeName)
}

// deleteOrEvictPod evicts the pod via the policy/v1 eviction subresource, and
// falls back to a direct delete when eviction is rejected (e.g. a
// PodDisruptionBudget blocks it) so teardown is not blocked.
func deleteOrEvictPod(ctx context.Context, clientset workloadClientset, pod *corev1.Pod) error {
	err := clientset.Evictions(pod.Namespace).Evict(ctx, &policyv1.Eviction{
		ObjectMeta: metav1.ObjectMeta{Name: pod.Name, Namespace: pod.Namespace},
	})
	if err == nil {
		return nil
	}

	// Eviction rejected (TooManyRequests from a PDB, or the eviction API is
	// unavailable): force-delete the pod directly so teardown proceeds.
	if apierrors.IsTooManyRequests(err) || apierrors.IsForbidden(err) {
		var gracePeriod int64

		return clientset.Pods(pod.Namespace).Delete(ctx, pod.Name, metav1.DeleteOptions{
			GracePeriodSeconds: &gracePeriod,
		})
	}

	return fmt.Errorf("failed to evict pod %s/%s: %w", pod.Namespace, pod.Name, err)
}

// waitForPodsGone polls until no non-daemonset, non-mirror, non-terminating
// pods remain on the Node, or the context expires.
func waitForPodsGone(ctx context.Context, clientset workloadClientset, nodeName string) error {
	for {
		pods, err := clientset.Pods(corev1.NamespaceAll).List(ctx, metav1.ListOptions{
			FieldSelector: fields.SelectorFromSet(fields.Set{"spec.nodeName": nodeName}).String(),
		})
		if err != nil {
			return fmt.Errorf("failed to list pods on node %s: %w", nodeName, err)
		}

		remaining := 0

		for _, pod := range pods.Items {
			if isDaemonSetPod(&pod) || isMirrorPod(&pod) || isTerminating(&pod) {
				continue
			}

			remaining++
		}

		if remaining == 0 {
			return nil
		}

		select {
		case <-ctx.Done():
			return fmt.Errorf("%w: %d pods still on node %s", ErrDrainTimeout, remaining, nodeName)
		case <-time.After(drainPodPollInterval):
		}
	}
}

func isDaemonSetPod(pod *corev1.Pod) bool {
	for _, ref := range pod.OwnerReferences {
		if ref.Controller != nil && *ref.Controller && ref.Kind == daemonSetController {
			return true
		}
	}

	return false
}

func isMirrorPod(pod *corev1.Pod) bool {
	_, ok := pod.Annotations[mirrorPodAnnotation]

	return ok
}

func isTerminating(pod *corev1.Pod) bool {
	return pod.DeletionTimestamp != nil
}
